arch: amd64
os: linux
dist: focal

language: c

compiler:
- gcc
- clang

services:
- docker

archlinux:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - procps-ng
  - reflector
  - screenfetch-git
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  - ~/.ccache:~/.ccache
# test space character in path
  - $HOME/y ay:$HOME/y ay
  before_install:
  - sudo sed -i '/#MAKEFLAGS=/c MAKEFLAGS="-j2"' /etc/makepkg.conf
  script:
  - sudo screenfetch
  - reflector --verbose -l 20 --sort rate -p https
  - echo $CC
  - touch test_file
  - |
    for ((i=0;i<10;i++)) ; do
      echo test$i
    done

before_install:
  - sudo apt-get update && sudo apt-get -y dist-upgrade
  - eval "$(GIMME_GO_VERSION=1.16 gimme)"
  - go version
  - sudo apt-get install --assume-yes libseccomp-dev
  - git clone https://github.com/opencontainers/runc
  - cd runc && git checkout v1.0.0-rc93 && make -j`nproc` && sudo make install && cd .. && rm -rf runc

script:
# build new image
- docker build --rm=true -t countstarlight/arch-travis:latest .
# run arch-travis to test new image
- bash ./arch-travis.sh
- ls -l

jobs:
  include:
  # push image to dockerhub
  - stage: build-push
    if: branch = master AND type != pull_request
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build --rm=true -t countstarlight/arch-travis:latest .
    - docker push countstarlight/arch-travis:latest
